//! Generated bindings to Valve's OpenVR flat C API.
//!
//! Nothing in this crate is hand-written. `build.rs` runs bindgen over `vendor/openvr_capi.h`
//! and the result is included below.
//!
//! Generated rather than transcribed, because the interface is a function-pointer table of
//! several hundred slots and a wrong slot is silent memory corruption rather than a compile
//! error. There is no version of that mistake that shows up as a red build.
//!
//! Vendoring Valve's own header is not a clean-room problem: it is the interface, not an
//! implementation. The license is in `vendor/LICENSE` and the attribution is in NOTICE.md.
//!
//! The safe wrapper does not live here. This crate is the raw surface, and everything in it is
//! `unsafe` to call.

#![allow(
    non_camel_case_types,
    non_upper_case_globals,
    non_snake_case,
    dead_code,
    clippy::all,
    reason = "generated by bindgen, and not ours to style"
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
